# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52f95af1f849cfb604892736c36d98b1ede26dd48f3cf30710165ba960088390e5b015951602d4421a0c53987a24ac955e119e10402179548be68bef07c9a08f

test:
  secret_key_base: 3e0ee4d282d95f2ad799636aef6812a02042897c14dd4fe7266d172076bf4a455d19834a65c3e8cdf26fce8c702950bda0ac82c463cd6e89e4d5ea34be83409b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
